# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow_login(object):
    basedir = os.path.dirname(__file__)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 647)
        MainWindow.setFixedSize(820,650)
        MainWindow.setStyleSheet("background-color: white; /* Fondo blanco */\n"
"        color: black; /* Letras negras */\n"
"        border-radius: 15px; /* Bordes redondeados */")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layout_imagen = QtWidgets.QWidget(parent=self.centralwidget)
        self.layout_imagen.setGeometry(QtCore.QRect(430, 0, 411, 651))
        self.layout_imagen.setObjectName("layout_imagen")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layout_imagen)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.layout_imagen)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(os.path.join(self.basedir, "icons_login/avion.jpg")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 411, 631))
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_widget = QtWidgets.QWidget()
        self.login_widget.setObjectName("login_widget")
        self.label = QtWidgets.QLabel(parent=self.login_widget)
        self.label.setGeometry(QtCore.QRect(10, 80, 401, 111))
        self.label.setStyleSheet("font: 700 35pt \"Unispace\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.login_widget)
        self.label_2.setGeometry(QtCore.QRect(20, 210, 131, 31))
        self.label_2.setObjectName("label_2")
        self.button_registrate_stacked = QtWidgets.QPushButton(parent=self.login_widget)
        self.button_registrate_stacked.setGeometry(QtCore.QRect(150, 210, 91, 31))
        self.button_registrate_stacked.setStyleSheet("background-color: #1B4965; /* Color #1B4965 */\n"
"        color: white; /* Letras blancas */\n"
"        border: none; /* Sin borde */\n"
"        padding: 5px 8px; /* Espaciado interno */\n"
"        border-radius: 10px; /* Bordes redondeados */\n"
"        height: 27px; /* Altura personalizada */\n"
"        font-size: 15px;")
        self.button_registrate_stacked.setObjectName("button_registrate_stacked")
        self.line_usuario_login = QtWidgets.QLineEdit(parent=self.login_widget)
        self.line_usuario_login.setGeometry(QtCore.QRect(10, 270, 351, 41))
        self.line_usuario_login.setStyleSheet("        background-color: rgba(255, 255, 255, 50%); /* Fondo transparente */\n"
"        border-bottom: 1px solid black; /* Borde inferior */\n"
"        border-radius: 5px; /* Bordes redondeados */\n"
"        color: black; /* Letras negras */\n"
"        height: 30px; /* Altura personalizada */\n"
"        font-size: 13px;")
        self.line_usuario_login.setObjectName("line_usuario_login")
        self.line_password_login = QtWidgets.QLineEdit(parent=self.login_widget)
        self.line_password_login.setGeometry(QtCore.QRect(10, 320, 351, 41))
        self.line_password_login.setStyleSheet("        background-color: rgba(255, 255, 255, 50%); /* Fondo transparente */\n"
"        border-bottom: 1px solid black; /* Borde inferior */\n"
"        border-radius: 5px; /* Bordes redondeados */\n"
"        color: black; /* Letras negras */\n"
"        height: 30px; /* Altura personalizada */\n"
"        font-size: 13px;")
        self.line_password_login.setObjectName("line_password_login")
        self.line_password_login.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.button_ver_password = QtWidgets.QPushButton(parent=self.login_widget)
        self.button_ver_password.setGeometry(QtCore.QRect(370, 320, 41, 41))
        self.button_ver_password.setStyleSheet("background-color: #1B4965; /* Color #1B4965 */\n"
"        color: white; /* Letras blancas */\n"
"        border: none; /* Sin borde */\n"
"        padding: 5px 8px; /* Espaciado interno */\n"
"        border-radius: 10px; /* Bordes redondeados */\n"
"        height: 27px; /* Altura personalizada */\n"
"        font-size: 15px;")
        self.button_ver_password.setText("")
        # Reemplaza esta parte de tu código
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(self.basedir, "icons_login/ojo-cerrado-morado.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_ver_password.setIcon(icon)
        self.button_ver_password.setObjectName("button_ver_password")
        self.button_inicia_sesion = QtWidgets.QPushButton(parent=self.login_widget)
        self.button_inicia_sesion.setGeometry(QtCore.QRect(10, 380, 401, 41))
        self.button_inicia_sesion.setStyleSheet("background-color: rgb(27, 73, 101);\n"
"\n"
"background-color: #1B4965; /* Color #1B4965 */\n"
"        color: white; /* Letras blancas */\n"
"        border: none; /* Sin borde */\n"
"        padding: 5px 8px; /* Espaciado interno */\n"
"        border-radius: 10px; /* Bordes redondeados */\n"
"        height: 27px; /* Altura personalizada */\n"
"        font-size: 15px;\n"
"")
        self.button_inicia_sesion.setObjectName("button_inicia_sesion")
        self.stackedWidget.addWidget(self.login_widget)
        self.singup_widget = QtWidgets.QWidget()
        self.singup_widget.setObjectName("singup_widget")
        self.label_4 = QtWidgets.QLabel(parent=self.singup_widget)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 381, 121))
        self.label_4.setStyleSheet("font: 700 35pt \"Unispace\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.singup_widget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 131, 31))
        self.label_5.setObjectName("label_5")
        self.line_nombre_registro = QtWidgets.QLineEdit(parent=self.singup_widget)
        self.line_nombre_registro.setGeometry(QtCore.QRect(10, 260, 191, 31))
        self.line_nombre_registro.setStyleSheet("        background-color: rgba(255, 255, 255, 50%); /* Fondo transparente */\n"
"        border-bottom: 1px solid black; /* Borde inferior */\n"
"        border-radius: 5px; /* Bordes redondeados */\n"
"        color: black; /* Letras negras */\n"
"        height: 30px; /* Altura personalizada */\n"
"        font-size: 13px;")
        self.line_nombre_registro.setObjectName("line_nombre_registro")
        self.line_apellido_registro = QtWidgets.QLineEdit(parent=self.singup_widget)
        self.line_apellido_registro.setGeometry(QtCore.QRect(220, 260, 191, 31))
        self.line_apellido_registro.setStyleSheet("        background-color: rgba(255, 255, 255, 50%); /* Fondo transparente */\n"
"        border-bottom: 1px solid black; /* Borde inferior */\n"
"        border-radius: 5px; /* Bordes redondeados */\n"
"        color: black; /* Letras negras */\n"
"        height: 30px; /* Altura personalizada */\n"
"        font-size: 13px;")
        self.line_apellido_registro.setObjectName("line_apellido_registro")
        self.line_email = QtWidgets.QLineEdit(parent=self.singup_widget)
        self.line_email.setGeometry(QtCore.QRect(10, 310, 401, 31))
        self.line_email.setStyleSheet("        background-color: rgba(255, 255, 255, 50%); /* Fondo transparente */\n"
"        border-bottom: 1px solid black; /* Borde inferior */\n"
"        border-radius: 5px; /* Bordes redondeados */\n"
"        color: black; /* Letras negras */\n"
"        height: 30px; /* Altura personalizada */\n"
"        font-size: 13px;")
        self.line_email.setObjectName("line_email")
        self.line_password_registro = QtWidgets.QLineEdit(parent=self.singup_widget)
        self.line_password_registro.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_password_registro.setGeometry(QtCore.QRect(10, 360, 351, 31))
        self.line_password_registro.setStyleSheet("        background-color: rgba(255, 255, 255, 50%); /* Fondo transparente */\n"
"        border-bottom: 1px solid black; /* Borde inferior */\n"
"        border-radius: 5px; /* Bordes redondeados */\n"
"        color: black; /* Letras negras */\n"
"        height: 30px; /* Altura personalizada */\n"
"        font-size: 13px;")
        self.line_password_registro.setObjectName("line_password_registro")
        self.line_password_validacion_registro = QtWidgets.QLineEdit(parent=self.singup_widget)
        self.line_password_validacion_registro.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_password_validacion_registro.setGeometry(QtCore.QRect(10, 410, 351, 31))
        self.line_password_validacion_registro.setStyleSheet("        background-color: rgba(255, 255, 255, 50%); /* Fondo transparente */\n"
"        border-bottom: 1px solid black; /* Borde inferior */\n"
"        border-radius: 5px; /* Bordes redondeados */\n"
"        color: black; /* Letras negras */\n"
"        height: 30px; /* Altura personalizada */\n"
"        font-size: 13px;")
        self.line_password_validacion_registro.setObjectName("line_password_validacion_registro")
        self.button_inicia_sesion_stacked = QtWidgets.QPushButton(parent=self.singup_widget)
        self.button_inicia_sesion_stacked.setGeometry(QtCore.QRect(150, 200, 101, 31))
        self.button_inicia_sesion_stacked.setStyleSheet("background-color: #1B4965; /* Color #1B4965 */\n"
"        color: white; /* Letras blancas */\n"
"        border: none; /* Sin borde */\n"
"        padding: 5px 8px; /* Espaciado interno */\n"
"        border-radius: 10px; /* Bordes redondeados */\n"
"        height: 27px; /* Altura personalizada */\n"
"        font-size: 15px;")
        self.button_inicia_sesion_stacked.setObjectName("button_inicia_sesion_stacked")
        self.button_registrarse = QtWidgets.QPushButton(parent=self.singup_widget)
        self.button_registrarse.setGeometry(QtCore.QRect(10, 450, 401, 41))
        self.button_registrarse.setStyleSheet("background-color: #1B4965; /* Color #1B4965 */\n"
"        color: white; /* Letras blancas */\n"
"        border: none; /* Sin borde */\n"
"        padding: 5px 8px; /* Espaciado interno */\n"
"        border-radius: 10px; /* Bordes redondeados */\n"
"        height: 27px; /* Altura personalizada */\n"
"        font-size: 15px;")
        self.button_registrarse.setObjectName("button_registrarse")
        self.button_ver_password_registro = QtWidgets.QPushButton(parent=self.singup_widget)
        self.button_ver_password_registro.setGeometry(QtCore.QRect(370, 350, 41, 41))
        
        self.button_ver_password_registro.setStyleSheet("background-color: #1B4965; /* Color #1B4965 */\n"
"        color: white; /* Letras blancas */\n"
"        border: none; /* Sin borde */\n"
"        padding: 5px 8px; /* Espaciado interno */\n"
"        border-radius: 10px; /* Bordes redondeados */\n"
"        height: 27px; /* Altura personalizada */\n"
"        font-size: 15px;")
        self.button_ver_password_registro.setText("")
        icon_ver = QtGui.QIcon()
        icon_ver.addPixmap(QtGui.QPixmap(os.path.join(self.basedir, "icons_login/ojo-cerrado-morado.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_ver_password_registro.setIcon(icon_ver)
        self.button_ver_password_registro.setObjectName("button_ver_password_registro")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.singup_widget)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 400, 41, 41))
        self.pushButton_7.setStyleSheet("background-color: #1B4965; /* Color #1B4965 */\n"
"        color: white; /* Letras blancas */\n"
"        border: none; /* Sin borde */\n"
"        padding: 5px 8px; /* Espaciado interno */\n"
"        border-radius: 10px; /* Bordes redondeados */\n"
"        height: 27px; /* Altura personalizada */\n"
"        font-size: 15px;")
        self.pushButton_7.setText("")
        icon_ver_veri = QtGui.QIcon()
        icon_ver_veri.addPixmap(QtGui.QPixmap(os.path.join(self.basedir, "icons_login/ojo-cerrado-morado.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon_ver_veri)
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.singup_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Inicia Sesion!"))
        self.label_2.setText(_translate("MainWindow", "¿No tienes una cuenta?"))
        self.button_registrate_stacked.setText(_translate("MainWindow", "Registrate"))
        self.line_usuario_login.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.line_password_login.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.button_inicia_sesion.setText(_translate("MainWindow", "Iniciar Sesion"))
        self.label_4.setText(_translate("MainWindow", "Registrate!"))
        self.label_5.setText(_translate("MainWindow", "¿Ya tienes una cuenta?"))
        self.line_nombre_registro.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.line_apellido_registro.setPlaceholderText(_translate("MainWindow", "Apellido"))
        self.line_email.setPlaceholderText(_translate("MainWindow", "Email (recuerda este sera tu usuario)"))
        self.line_password_registro.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.line_password_validacion_registro.setPlaceholderText(_translate("MainWindow", "Repite la Contraseña"))
        self.button_inicia_sesion_stacked.setText(_translate("MainWindow", "Inicia sesion"))
        self.button_registrarse.setText(_translate("MainWindow", "Registrate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
